### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by GunsForGuns** [dksrphm/jvgmtrans#3]
I have not experience with java of any kind and have 0 idea on how to even use this. I tried just running the .bat file but keep getting errors. Am I missing something or doing it wrong any help would be nice.

**Comment by dksrphm** [comment]
I added build.xml (for Apache ant) to build this tool.
And I added jvgmtrans.bat to run tools.

**Comment by GunsForGuns** [comment]
I think I built it but I keep getting an error saying "Could not find or load main class jvgmtrans.jvgmtrans" I am trying to just run the .bat file in cmd. do I need to run it some other way? I'm not sure I even built it right I did use Apache ant after reading about it for 30 min and looking at the files it seems to turned all the .java files in the bin folder to .class files. I'm really not sure if that is right. I wish I was more experienced in this kind of stuff so I wouldn't have to waste your time lol but I have no idea what I'm doing here. Basically ended up here after a few days of searching for a way to get hot dog storms stage 1 theme as a .midi

**Comment by dksrphm** [comment]
I released binary archive:
jvgmtrans_20220419.zip

.java, .bat, and .class files are there.

I guess this will work.

**Comment by GunsForGuns** [comment]
I apologize for wasting your time and being such an idiot but I'm still getting the same issue even with the binary archive thingy
![image](https://user-images.githubusercontent.com/101996331/164046156-1978124b-2679-4ce2-ac06-2d25538d2ff0.png)
I have no clue what I'm doing wrong.

**Comment by dksrphm** [comment]
Thank you for report.
Please set current directory to jvgmtrans_xxx(where jvgmtrans.bat is exist) and put vgm file to same directory,
and erase blanks in vgm file name.

Is it work?
\> cd C:\Users\GunsForGuns\Music\jvgmtrans_20220419
\> copy "C:\Users\GunsForGuns\Music04 Stage 1.vgm" .
\> rename "Music04 Stage 1.vgm" "Music04Stage1.vgm"
\> jvgmtrans.bat Music04Stage1.vgm

I also tried to convert "Hotdog storm stage 1" vgm to midi.
1. I got vgm file from here: https://vgmrips.net/packs/pack/hotdog-storm-arcade
2. Extract Hotdog_Storm_(Arcade).zip. You will get "04 Stage 1.vgz"(15,112byte). I used 7-zip to extract.
3. Extend "04 Stage 1.vgz". You will get "04 Stage 1"(87,565byte). This is vgm format file in YM2203.
4. Rename "04 Stage 1" -> "04Stage1". (Erase blanks in file name. Some day I will update...?)
5. jvgmtrans.bat 04Stage1 -> You will get 04Stage1_YM2203.mid(29,319byte)

04Stage1_YM2203.mid sounds like as below:

CH1 -> Percussion. Sounds not good. You must re-write in drum track to hear correctly.

- Note no 72 -> maybe snare drum
- Note no 24 -> maybe bass drum
- Note no 64 etc. -> maybe tom

CH2 -> Bass
CH3 -> Melody
CH4 -> Back1
CH5 -> Back2
CH6 -> Delay effect of CH3-5

**Comment by GunsForGuns** [comment]
It works!!! thank you so much for your help :3 I am very happy to finally see a .midi file :D

**Comment by dksrphm** [comment]
Thank you for your report.

I need update batch files(?) to be able to run in relative path.
